### ISSUE TITLE
Reporte de práctica Architect. Fernando Miguel López.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-architect-Ferch0419#1]
[Práctica Architect Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Ferch0419/files/7173027/Practica.Architect.Fernando.Miguel.Lopez.pdf)

**Comment by Band-hi** [comment]
calificación: 20/20
 - Contiene todo lo de la rubrica
 - Se explica bien los procesos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
